### ISSUE TITLE
Maven artifacts are empty

### ISSUE THREAD

**Issue by fredericOfTestfabrik** [ajozwik/pekko-smtp-server#3]
Hi,

I wanted to try out your library and added the dependency from maven central. Unfortunately, the artifact you pushed to maven central only contains a MANIFEST.MF, so something appears to have gone wrong during the build of your artifact.

See:
https://repo1.maven.org/maven2/com/github/ajozwik/akka-smtp-server_2.12/0.2.1.1/

**Comment by ajozwik** [comment]
I see the files. Maybe there are unavailable in your location?

**Comment by fredericOfTestfabrik** [comment]
The files are there but they only contain a Manifest File, no code.

**Comment by ajozwik** [comment]
Please use:
```
libraryDependencies += "com.github.ajozwik" %% "akka-smtp" % "0.2.1.1"
```
